[project]
name = "virtual-world-mcp"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = []
[[tool.uv.index]]
url="https://pypi.tuna.tsinghua.edu.cn/simple"
default=true